# Generated by Django 3.2.8 on 2021-10-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('TradesMan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktrademan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='booktrademan',
            name='trade_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradesMan.tradesman'),
        ),
    ]
