# Generated by Django 3.2.8 on 2021-10-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='imagepath',
            field=models.ImageField(blank=True, null=True, upload_to='profilePic'),
        ),
    ]
