# Generated by Django 3.2.8 on 2021-10-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_imageupload_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
